/**
 * Canonical S-01..S-99 traceability metadata (SAATHI-344).
 * Source of truth: docs/design/v3.2/LegalSaathi Student Module Option J S01-S99 Traceability Matrix v3.2.md
 * Generated for the reviewer/dev TraceabilityBanner — screen ID, PRD epic/story mapping, release tranche, persona.
 */
export interface TraceEntry {
  id: string;
  epic: string;
  story: string;
  release: string;
  persona: string;
}

export const traceability: Record<string, TraceEntry> = {
  'S-01': { id: 'S-01', epic: 'S1', story: 'Launch, login, registration & OTP', release: 'R1', persona: 'all' },
  'S-02': { id: 'S-02', epic: 'S1', story: 'Launch, login, registration & OTP', release: 'R1', persona: 'all' },
  'S-03': { id: 'S-03', epic: 'S1', story: 'Launch, login, registration & OTP', release: 'R1', persona: 'all' },
  'S-04': { id: 'S-04', epic: 'S1', story: 'Launch, login, registration & OTP', release: 'R1', persona: 'all' },
  'S-05': { id: 'S-05', epic: 'S1', story: 'Launch, login, registration & OTP', release: 'R1', persona: 'all' },
  'S-06': { id: 'S-06', epic: 'S1', story: 'Launch, login, registration & OTP', release: 'R1', persona: 'all' },
  'S-07': { id: 'S-07', epic: 'S1', story: 'Launch, login, registration & OTP', release: 'R1', persona: 'all' },
  'S-08': { id: 'S-08', epic: 'S1', story: 'Launch, login, registration & OTP', release: 'R1', persona: 'all' },
  'S-09': { id: 'S-09', epic: 'S2', story: 'Three-step profile setup', release: 'R1', persona: 'all' },
  'S-10': { id: 'S-10', epic: 'S2', story: 'Three-step profile setup', release: 'R1', persona: 'all' },
  'S-11': { id: 'S-11', epic: 'S2', story: 'Three-step profile setup', release: 'R1', persona: 'all' },
  'S-12': { id: 'S-12', epic: 'S2', story: 'Three-step profile setup', release: 'R1', persona: 'all' },
  'S-13': { id: 'S-13', epic: 'S2', story: 'Three-step profile setup', release: 'R1', persona: 'all' },
  'S-14': { id: 'S-14', epic: 'S3', story: 'Dashboard, profile, settings & privacy', release: 'R1', persona: 'all' },
  'S-15': { id: 'S-15', epic: 'S3', story: 'Dashboard, profile, settings & privacy', release: 'R1', persona: 'all' },
  'S-16': { id: 'S-16', epic: 'S3', story: 'Dashboard, profile, settings & privacy', release: 'R1', persona: 'all' },
  'S-17': { id: 'S-17', epic: 'S3', story: 'Dashboard, profile, settings & privacy', release: 'R1', persona: 'all' },
  'S-18': { id: 'S-18', epic: 'S3', story: 'Dashboard, profile, settings & privacy', release: 'R1', persona: 'all' },
  'S-19': { id: 'S-19', epic: 'S3', story: 'Dashboard, profile, settings & privacy', release: 'R1', persona: 'all' },
  'S-20': { id: 'S-20', epic: 'S4', story: 'Discover, apply & track internships', release: 'R1', persona: 'Law Student' },
  'S-21': { id: 'S-21', epic: 'S4', story: 'Discover, apply & track internships', release: 'R1', persona: 'Law Student' },
  'S-22': { id: 'S-22', epic: 'S4', story: 'Discover, apply & track internships', release: 'R1', persona: 'Law Student' },
  'S-23': { id: 'S-23', epic: 'S4', story: 'Discover, apply & track internships', release: 'R1', persona: 'Law Student' },
  'S-24': { id: 'S-24', epic: 'S4', story: 'Discover, apply & track internships', release: 'R1', persona: 'Law Student' },
  'S-25': { id: 'S-25', epic: 'S4', story: 'Discover, apply & track internships', release: 'R1', persona: 'Law Student' },
  'S-26': { id: 'S-26', epic: 'S4', story: 'Discover, apply & track internships', release: 'R1', persona: 'Law Student' },
  'S-27': { id: 'S-27', epic: 'S5', story: 'Search, compare & follow law schools', release: 'R3', persona: 'CLAT, Law' },
  'S-28': { id: 'S-28', epic: 'S5', story: 'Search, compare & follow law schools', release: 'R3', persona: 'CLAT, Law' },
  'S-29': { id: 'S-29', epic: 'S5', story: 'Search, compare & follow law schools', release: 'R3', persona: 'CLAT, Law' },
  'S-30': { id: 'S-30', epic: 'S5', story: 'Search, compare & follow law schools', release: 'R3', persona: 'CLAT, Law' },
  'S-31': { id: 'S-31', epic: 'S6', story: 'Tutor discovery, booking & reviews', release: 'R2', persona: 'all' },
  'S-32': { id: 'S-32', epic: 'S6', story: 'Tutor discovery, booking & reviews', release: 'R2', persona: 'all' },
  'S-33': { id: 'S-33', epic: 'S6', story: 'Tutor discovery, booking & reviews', release: 'R2', persona: 'all' },
  'S-34': { id: 'S-34', epic: 'S6', story: 'Tutor discovery, booking & reviews', release: 'R2', persona: 'all' },
  'S-35': { id: 'S-35', epic: 'S6', story: 'Tutor discovery, booking & reviews', release: 'R2', persona: 'all' },
  'S-36': { id: 'S-36', epic: 'S7', story: 'AI legal research (citations & guardrails)', release: 'R2', persona: 'Law/Grad/Jud' },
  'S-37': { id: 'S-37', epic: 'S7', story: 'AI legal research (citations & guardrails)', release: 'R2', persona: 'Law/Grad/Jud' },
  'S-38': { id: 'S-38', epic: 'S7', story: 'AI legal research (citations & guardrails)', release: 'R2', persona: 'Law/Grad/Jud' },
  'S-39': { id: 'S-39', epic: 'S7', story: 'AI legal research (citations & guardrails)', release: 'R2', persona: 'Law/Grad/Jud' },
  'S-40': { id: 'S-40', epic: 'S7', story: 'AI legal research (citations & guardrails)', release: 'R2', persona: 'Law/Grad/Jud' },
  'S-41': { id: 'S-41', epic: 'S8', story: 'Moot practice workspace', release: 'R2', persona: 'Law Student' },
  'S-42': { id: 'S-42', epic: 'S8', story: 'Moot practice workspace', release: 'R2', persona: 'Law Student' },
  'S-43': { id: 'S-43', epic: 'S8', story: 'Moot practice workspace', release: 'R2', persona: 'Law Student' },
  'S-44': { id: 'S-44', epic: 'S8', story: 'Moot practice workspace', release: 'R2', persona: 'Law Student' },
  'S-45': { id: 'S-45', epic: 'S8', story: 'Moot practice workspace', release: 'R2', persona: 'Law Student' },
  'S-46': { id: 'S-46', epic: 'S9', story: 'Case digests, flashcards & quizzes', release: 'R2', persona: 'all' },
  'S-47': { id: 'S-47', epic: 'S9', story: 'Case digests, flashcards & quizzes', release: 'R2', persona: 'all' },
  'S-48': { id: 'S-48', epic: 'S9', story: 'Case digests, flashcards & quizzes', release: 'R2', persona: 'all' },
  'S-49': { id: 'S-49', epic: 'S9', story: 'Case digests, flashcards & quizzes', release: 'R2', persona: 'all' },
  'S-50': { id: 'S-50', epic: 'S10', story: 'Moderated community & forums', release: 'R1', persona: 'all' },
  'S-51': { id: 'S-51', epic: 'S10', story: 'Moderated community & forums', release: 'R1', persona: 'all' },
  'S-52': { id: 'S-52', epic: 'S10', story: 'Moderated community & forums', release: 'R1', persona: 'all' },
  'S-53': { id: 'S-53', epic: 'S10', story: 'Moderated community & forums', release: 'R1', persona: 'all' },
  'S-54': { id: 'S-54', epic: 'S10', story: 'Moderated community & forums', release: 'R1', persona: 'all' },
  'S-55': { id: 'S-55', epic: 'S11', story: 'Exam prep (CLAT/AIBE/Judiciary)', release: 'R1/R2', persona: 'all' },
  'S-56': { id: 'S-56', epic: 'S11', story: 'Exam prep (CLAT/AIBE/Judiciary)', release: 'R1/R2', persona: 'all' },
  'S-57': { id: 'S-57', epic: 'S11', story: 'Exam prep (CLAT/AIBE/Judiciary)', release: 'R1/R2', persona: 'all' },
  'S-58': { id: 'S-58', epic: 'S11', story: 'Exam prep (CLAT/AIBE/Judiciary)', release: 'R1/R2', persona: 'all' },
  'S-59': { id: 'S-59', epic: 'S11', story: 'Exam prep (CLAT/AIBE/Judiciary)', release: 'R1/R2', persona: 'all' },
  'S-60': { id: 'S-60', epic: 'S11', story: 'Exam prep (CLAT/AIBE/Judiciary)', release: 'R1/R2', persona: 'all' },
  'S-61': { id: 'S-61', epic: 'S12', story: 'Clinical hours log & verification', release: 'R1', persona: 'Law Student' },
  'S-62': { id: 'S-62', epic: 'S12', story: 'Clinical hours log & verification', release: 'R1', persona: 'Law Student' },
  'S-63': { id: 'S-63', epic: 'S12', story: 'Clinical hours log & verification', release: 'R1', persona: 'Law Student' },
  'S-64': { id: 'S-64', epic: 'S12', story: 'Clinical hours log & verification', release: 'R1', persona: 'Law Student' },
  'S-65': { id: 'S-65', epic: 'S12', story: 'Clinical hours log & verification', release: 'R1', persona: 'Law Student' },
  'S-66': { id: 'S-66', epic: 'S13', story: 'Career & job hub', release: 'R2', persona: 'Law, Grad' },
  'S-67': { id: 'S-67', epic: 'S13', story: 'Career & job hub', release: 'R2', persona: 'Law, Grad' },
  'S-68': { id: 'S-68', epic: 'S13', story: 'Career & job hub', release: 'R2', persona: 'Law, Grad' },
  'S-69': { id: 'S-69', epic: 'S13', story: 'Career & job hub', release: 'R2', persona: 'Law, Grad' },
  'S-70': { id: 'S-70', epic: 'S13', story: 'Career & job hub', release: 'R2', persona: 'Law, Grad' },
  'S-71': { id: 'S-71', epic: 'S14', story: 'LLM & study-abroad planner', release: 'R3', persona: 'Law, Grad' },
  'S-72': { id: 'S-72', epic: 'S14', story: 'LLM & study-abroad planner', release: 'R3', persona: 'Law, Grad' },
  'S-73': { id: 'S-73', epic: 'S14', story: 'LLM & study-abroad planner', release: 'R3', persona: 'Law, Grad' },
  'S-74': { id: 'S-74', epic: 'S14', story: 'LLM & study-abroad planner', release: 'R3', persona: 'Law, Grad' },
  'S-75': { id: 'S-75', epic: 'S15', story: 'Study groups & shared notes', release: 'R1.1', persona: 'all' },
  'S-76': { id: 'S-76', epic: 'S15', story: 'Study groups & shared notes', release: 'R1.1', persona: 'all' },
  'S-77': { id: 'S-77', epic: 'S15', story: 'Study groups & shared notes', release: 'R1.1', persona: 'all' },
  'S-78': { id: 'S-78', epic: 'S15', story: 'Study groups & shared notes', release: 'R1.1', persona: 'all' },
  'S-79': { id: 'S-79', epic: 'S16', story: 'Multi-moot portfolio', release: 'R2', persona: 'Law Student' },
  'S-80': { id: 'S-80', epic: 'S16', story: 'Multi-moot portfolio', release: 'R2', persona: 'Law Student' },
  'S-81': { id: 'S-81', epic: 'S16', story: 'Multi-moot portfolio', release: 'R2', persona: 'Law Student' },
  'S-82': { id: 'S-82', epic: 'S17', story: 'Credential wallet & portfolio', release: 'R3', persona: 'Law, Grad' },
  'S-83': { id: 'S-83', epic: 'S17', story: 'Credential wallet & portfolio', release: 'R3', persona: 'Law, Grad' },
  'S-84': { id: 'S-84', epic: 'S17', story: 'Credential wallet & portfolio', release: 'R3', persona: 'Law, Grad' },
  'S-85': { id: 'S-85', epic: 'S17', story: 'Credential wallet & portfolio', release: 'R3', persona: 'Law, Grad' },
  'S-86': { id: 'S-86', epic: 'S18', story: 'Internship experience reporting', release: 'R1.1', persona: 'Law Student' },
  'S-87': { id: 'S-87', epic: 'S18', story: 'Internship experience reporting', release: 'R1.1', persona: 'Law Student' },
  'S-88': { id: 'S-88', epic: 'S18', story: 'Internship experience reporting', release: 'R1.1', persona: 'Law Student' },
  'S-89': { id: 'S-89', epic: 'S18', story: 'Internship experience reporting', release: 'R1.1', persona: 'Law Student' },
  'S-90': { id: 'S-90', epic: 'S19', story: 'Unified calendar & reminders', release: 'R1', persona: 'all' },
  'S-91': { id: 'S-91', epic: 'S19', story: 'Unified calendar & reminders', release: 'R1', persona: 'all' },
  'S-92': { id: 'S-92', epic: 'S19', story: 'Unified calendar & reminders', release: 'R1', persona: 'all' },
  'S-93': { id: 'S-93', epic: 'S19', story: 'Unified calendar & reminders', release: 'R1', persona: 'all' },
  'S-94': { id: 'S-94', epic: 'S20', story: 'Drafting practice lab', release: 'R2', persona: 'Law/Grad/Jud' },
  'S-95': { id: 'S-95', epic: 'S20', story: 'Drafting practice lab', release: 'R2', persona: 'Law/Grad/Jud' },
  'S-96': { id: 'S-96', epic: 'S20', story: 'Drafting practice lab', release: 'R2', persona: 'Law/Grad/Jud' },
  'S-97': { id: 'S-97', epic: 'S21', story: 'Graduate transition & lawyer upgrade', release: 'R3', persona: 'Graduate' },
  'S-98': { id: 'S-98', epic: 'S21', story: 'Graduate transition & lawyer upgrade', release: 'R3', persona: 'Graduate' },
  'S-99': { id: 'S-99', epic: 'S21', story: 'Graduate transition & lawyer upgrade', release: 'R3', persona: 'Graduate' },
};

export const TRACE_COUNT = Object.keys(traceability).length;

export function getTrace(screenId: string): TraceEntry | undefined {
  return traceability[screenId?.toUpperCase()];
}
