"""ORM models. Importing this package registers all tables on Base.metadata."""
from app.db.models.audit import AuditEvent  # noqa: F401  (shared audit_events table)
from app.models.wave1 import (  # noqa: F401
    ComparisonItem, ComparisonSet, DataSubjectRequest, DeletionJob, ExportJob,
    LawSchool, LawSchoolFact, LawSchoolFollow, LawSchoolProgramme, LawSchoolSource,
    PrivacyPreference, SavedLawSchool, UserSettings,
)
from app.models.registration import (  # noqa: F401
    Consent,
    AuthSession,
    GuardianConsent,
    LoginAttempt,
    OtpChallenge,
    OtpOutbox,
    RegistrationIdempotencyRecord,
    RegistrationDobReconciliation,
    RecoverySession,
    StudentProfile,
    StudentRegistration,
    StudentVerification,
    User,
)
from app.models.wave2 import (  # noqa: F401
    BookingEvent, BookingHold, PaymentEvent, PaymentOrder, PaymentRefund,
    ReviewModeration, SessionAttendance, SessionCancellation,
    SessionReminderJob, SessionStatusHistory, TutorAvailabilitySlot,
    TutorProfile, TutorReview, TutorSubject, TutoringOutbox, TutoringSession,
    VideoSessionGrant,
)
from app.models.credentials import (  # noqa: F401
    Credential, CredentialEvidence, CredentialEvidenceScanEvent,
    CredentialIssuer, CredentialOutbox, CredentialReminderJob,
    CredentialRevocation, CredentialShareProjection, CredentialStatusHistory,
    CredentialVerificationEvent, IssuerAuthorisation, VerificationAccessLog,
    VerificationToken,
)
from app.models.wave4 import (  # noqa: F401
    DuplicateCluster,
    DuplicateClusterMember,
    InternshipReport,
    InternshipReportCategory,
    InternshipReportConsent,
    InternshipReportEvidence,
    InternshipReportingOutbox,
    ModerationAction,
    ModerationAssignment,
    ModerationCase,
    ModerationHandoff,
    ModerationNotificationOutbox,
    NotificationOutbox,
    OrganisationResponse,
    OrganisationResponseRequest,
    PublicationDecision,
    PublishedRiskLabel,
    ReporterIdentityAccessApproval,
    ReporterIdentityAccessRequest,
    ReporterIdentityVault,
    RiskSignal,
    RiskSignalApproval,
    ResponseModeration,
)
from app.models.calendar import (  # noqa: F401
    CalendarConflict,
    CalendarEvent,
    CalendarEventSource,
    CalendarExportRevocation,
    CalendarExportSubscription,
    CalendarExportToken,
    CalendarReminderPreference,
    CalendarViewPreference,
)
from app.models.internships import (  # noqa: F401
    InternshipListing,
    SavedInternship,
)

__all__ = [
    "User",
    "AuthSession",
    "LoginAttempt",
    "StudentRegistration",
    "StudentProfile",
    "OtpChallenge",
    "OtpOutbox",
    "RegistrationIdempotencyRecord",
    "RegistrationDobReconciliation",
    "RecoverySession",
    "Consent",
    "StudentVerification",
    "GuardianConsent",
    "AuditEvent",
    "CredentialIssuer",
    "Credential",
    "CredentialEvidence",
    "CredentialStatusHistory",
    "CredentialShareProjection",
    "CredentialOutbox",
    "CredentialReminderJob",
    "CredentialEvidenceScanEvent",
    "IssuerAuthorisation",
    "CredentialVerificationEvent",
    "VerificationToken",
    "CredentialRevocation",
    "VerificationAccessLog",
    # Wave 2 tutoring marketplace (SAATHI-123 / SAATHI-127)
    "TutorProfile",
    "TutorSubject",
    "TutorAvailabilitySlot",
    "BookingHold",
    "PaymentOrder",
    "PaymentEvent",
    "PaymentRefund",
    "TutoringSession",
    "BookingEvent",
    "SessionStatusHistory",
    "SessionAttendance",
    "SessionCancellation",
    "TutorReview",
    "ReviewModeration",
    "TutoringOutbox",
    "SessionReminderJob",
    "VideoSessionGrant",
    # Wave 4 private internship reporting (SAATHI-269 / SAATHI-450)
    "InternshipReport",
    "InternshipReportCategory",
    "InternshipReportConsent",
    "InternshipReportEvidence",
    "ReporterIdentityVault",
    "ReporterIdentityAccessRequest",
    "ReporterIdentityAccessApproval",
    "ModerationHandoff",
    "InternshipReportingOutbox",
    "ModerationCase",
    "ModerationAssignment",
    "ModerationAction",
    "DuplicateCluster",
    "DuplicateClusterMember",
    "RiskSignal",
    "RiskSignalApproval",
    "ModerationNotificationOutbox",
    "PublishedRiskLabel",
    "PublicationDecision",
    "OrganisationResponseRequest",
    "OrganisationResponse",
    "ResponseModeration",
    "NotificationOutbox",
    # Wave 5 unified calendar and interoperability (SAATHI-285/290/295)
    "CalendarEventSource",
    "CalendarEvent",
    "CalendarViewPreference",
    "CalendarReminderPreference",
    "CalendarConflict",
    "CalendarExportSubscription",
    "CalendarExportToken",
    "CalendarExportRevocation",
    # SAATHI-60 internship discovery and owner-scoped saves
    "InternshipListing",
    "SavedInternship",
]
