"""ORM models. Importing this package registers all tables on Base.metadata."""
from app.db.models.audit import AuditEvent  # noqa: F401  (shared audit_events table)
from app.models.wave1 import (  # noqa: F401
    ComparisonItem, ComparisonSet, DataSubjectRequest, DeletionJob, ExportJob,
    LawSchool, LawSchoolFact, LawSchoolFollow, LawSchoolProgramme, LawSchoolSource,
    PrivacyPreference, SavedLawSchool, UserSettings,
)
from app.models.registration import (  # noqa: F401
    Consent,
    AuthSession,
    GuardianConsent,
    LoginAttempt,
    OtpChallenge,
    OtpOutbox,
    RecoverySession,
    StudentProfile,
    StudentRegistration,
    StudentVerification,
    User,
)
from app.models.wave2 import (  # noqa: F401
    BookingEvent, BookingHold, PaymentEvent, PaymentOrder, PaymentRefund,
    ReviewModeration, SessionAttendance, SessionCancellation,
    SessionReminderJob, SessionStatusHistory, TutorAvailabilitySlot,
    TutorProfile, TutorReview, TutorSubject, TutoringOutbox, TutoringSession,
    VideoSessionGrant,
)
from app.models.credentials import (  # noqa: F401
    Credential, CredentialEvidence, CredentialEvidenceScanEvent,
    CredentialIssuer, CredentialOutbox, CredentialReminderJob,
    CredentialRevocation, CredentialShareProjection, CredentialStatusHistory,
    CredentialVerificationEvent, IssuerAuthorisation, VerificationAccessLog,
    VerificationToken,
)

__all__ = [
    "User",
    "AuthSession",
    "LoginAttempt",
    "StudentRegistration",
    "StudentProfile",
    "OtpChallenge",
    "OtpOutbox",
    "RecoverySession",
    "Consent",
    "StudentVerification",
    "GuardianConsent",
    "AuditEvent",
    "CredentialIssuer",
    "Credential",
    "CredentialEvidence",
    "CredentialStatusHistory",
    "CredentialShareProjection",
    "CredentialOutbox",
    "CredentialReminderJob",
    "CredentialEvidenceScanEvent",
    "IssuerAuthorisation",
    "CredentialVerificationEvent",
    "VerificationToken",
    "CredentialRevocation",
    "VerificationAccessLog",
    # Wave 2 tutoring marketplace (SAATHI-123 / SAATHI-127)
    "TutorProfile",
    "TutorSubject",
    "TutorAvailabilitySlot",
    "BookingHold",
    "PaymentOrder",
    "PaymentEvent",
    "PaymentRefund",
    "TutoringSession",
    "BookingEvent",
    "SessionStatusHistory",
    "SessionAttendance",
    "SessionCancellation",
    "TutorReview",
    "ReviewModeration",
    "TutoringOutbox",
    "SessionReminderJob",
    "VideoSessionGrant",
]
